name: Linux

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  linux-build-release:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        swift: ["latest"]
    container:
      image: swift:${{ matrix.swift }}
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4.2.2

      - name: Build Release
        run: swift build -c release

      - name: Upload build artifacts
        if: failure()
        uses: actions/upload-artifact@v3.1.2
        with:
          name: build-artifacts-${{ matrix.swift }}-${{ github.run_id }}
          path: |
            *.lcov
            .build/*.yaml
            .build/**/*.a
            .build/**/*.so
            .build/**/*.dylib
            .build/**/*.dSYM
            .build/**/*.json
