name: macOS

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  macOS-build-release:
    runs-on: macOS-11
    strategy:
      matrix:
        xcode: ["13.0"]
    steps:
      - name: Checkout
        uses: actions/checkout@v2.7.0

      - name: Select Xcode ${{ matrix.xcode }}
        run: sudo xcode-select -s /Applications/Xcode_${{ matrix.xcode }}.app

      - name: Build Release
        run: make build-release
        env:
          DEVELOPER_DIR: /Applications/Xcode_${{ matrix.xcode }}.app/Contents/Developer

      - name: Upload build artifacts
        if: failure()
        uses: actions/upload-artifact@v2.3.1
        with:
          name: build-artifacts-${{ matrix.xcode }}-${{ github.run_id }}
          path: |
            *.lcov
            .build/*.yaml
            .build/**/*.a
            .build/**/*.so
            .build/**/*.dylib
            .build/**/*.dSYM 
            .build/**/*.json
